server:
    port: 9992 # random port
    tomcat:
      connection:
        timeout: -1

spring:
  application:
        name: EgovSearch
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.cj.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://localhost:3306/com}
    username: ${datasource.username:com}
    password: ${datasource.password:com01}
    hikari:
      maximum-pool-size: ${datasource.hikari.maximum-pool-size:20}
      connection-timeout: ${datasource.hikari.connection-timeout:20000}
      idle-timeout: ${datasource.hikari.idle-timeout:30000}
      minimum-idle: ${datasource.hikari.minimum-idle:5}
      max-lifetime: ${datasource.hikari.max-lifetime:180000}
  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto:update}
    open-in-view: ${jpa.open-in-view:false}
    show-sql: ${jpa.show-sql:true}
    properties:
      hibernate:
        format_sql: ${jpa.properties.hibernate.format_sql:true}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        searchConsumer-in-0:
          destination: board-topic
          group: search-service
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
    function:
      definition: searchConsumer
  mvc:
    cors:
      allowed-origins: http://localhost:30992
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

logging:
  level:
    org:
      egovframe:
        rte: debug
      springframework:
        boot:
          autoconfigure: error
        web: debug
    egovframework:
      com: debug
      rte: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  version: v4.3.0
  packages-to-scan: egovframework
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls[0]:
      name: EgovOpenSearchAPI
      url: /v3/api-docs
    urls-primary-name: EgovOpenSearchAPI
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  cache:
    disabled: true

opensearch:
  protocol: https
  url: localhost
  port: 9200
  username: admin
  password: egovFrame123!@#
  keystore:
    path: ${OPENSEARCH_KEYSTORE_PATH:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/lib/security/cacerts}
    password: changeit
  text:
    indexname: text-bbs-index
  vector:
    indexname: vector-bbs-index

index:
  batch:
    size: 1000

egov:
  textsearch:
    count: 10
    page:
      size: 5
  vectorsearch:
    count: 5
    page:
      size: 5

app:
  search-config-path: ${APP_SEARCH_CONFIG_PATH:/config/searchConfig.json}

---
spring:
  config:
    activate:
      on-profile: k8s
    import: 'optional:configserver:' # Config 서버 비활성화
  cloud:
    config:
      enabled: false # Config 클라이언트 비활성화
    discovery:
      enabled: false # Eureka Discovery 비활성화

eureka:
  client:
    enabled: false # Eureka 클라이언트 비활성화

server:
  port: 80 # k8s 환경에서 모든 서비스가 80 포트 사용
