apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: jaeger-collector.egov-monitoring:9411
    enablePrometheusMerge: true
    extensionProviders:
    - name: otel-loki
      envoyOtelAls:
        service: otel-collector.egov-monitoring.svc.cluster.local
        port: 4317
        logFormat:
          labels:
            pod: "%ENVIRONMENT(POD_NAME)%"
            namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
            app: "%ENVIRONMENT(APP_CONTAINER_NAME)%"
            instance: "%ENVIRONMENT(HOSTNAME)%"
            version: "%ENVIRONMENT(POD_VERSION)%"
            cluster_name: "egov-cluster"
            log_type: "access-log"
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'