apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: egov-apps-telemetry
  namespace: egov-app
spec:
  accessLogging:
    - providers:
      - name: otel-loki
  tracing:
    - randomSamplingPercentage: 100.0
      providers:
        - name: "zipkin"
      customTags:
        environment:
          literal:
            value: "production"
  metrics:
    - providers:
        - name: prometheus