# hostPath PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-hostpath
  namespace: egov-infra
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${DATA_BASE_PATH}/rabbitmq"
    type: DirectoryOrCreate
  storageClassName: standard

---
# hostPath PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-hostpath
  namespace: egov-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
  volumeName: rabbitmq-pv-hostpath
