apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-cmmncode
  namespace: egov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-cmmncode
  template:
    metadata:
      labels:
        app: egov-cmmncode
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "15020"
    spec:
      containers:
      - name: egov-cmmncode
        image: egovcmmncode:k8s
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - configMapRef:
            name: egov-common-config
        - secretRef:
            name: mysql-secret
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "80"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: token.accessSecret
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_ACCESS_SECRET
        - name: token.refreshSecret
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_REFRESH_SECRET
        - name: token.accessExpiration
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_ACCESS_EXPIRATION
        - name: token.refreshExpiration
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_REFRESH_EXPIRATION
        - name: roles.roleAdmin
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: ROLES_ROLE_ADMIN
        - name: roles.roleUser
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: ROLES_ROLE_USER
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: egov-cmmncode
  namespace: egov-app
spec:
  selector:
    app: egov-cmmncode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
