apiVersion: v1
kind: ConfigMap
metadata:
  name: egov-common-config
  namespace: egov-app
data:
  # Database
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.egov-db.svc.cluster.local:3306/com"
  
  # HikariCP
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "1800000"
  
  # JPA
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  
  # Token Configuration
  TOKEN_ACCESS_SECRET: "7FB814B9D7FFB3D675EF1F525C1D61B254227B3B0A771DDDBDFE4112A1F42F66"
  TOKEN_REFRESH_SECRET: "7FB814B9D7FFB3D675EF1F525C1D61B254227B3B0A771DDDBDFE4112A1F42F66"
  TOKEN_ACCESS_EXPIRATION: "1200000"
  TOKEN_REFRESH_EXPIRATION: "3600000"
  
  # Roles
  ROLES_ROLE_ADMIN: "/uat/uap/**, /sec/ram/**, /sec/rgm/**, /sec/gmt/**, /sec/rmt/**, /cop/tpl/**, /uss/olp/qmc/**, /uss/olp/qtm/**, /uss/olp/qqm/**, /uss/olp/qim/**, /sym/ccm/cca/**, /sym/ccm/ccc/**, /sym/ccm/cde/**, /ext/ops/**, /a/b/c/**"
  ROLES_ROLE_USER: "/cop/bls/**, /cop/bbs/**, /cop/cmy/**, /cop/brd/**, /mip/**, /uss/olp/qri/**, /uss/olp/qrm/**, /a/b/c/**"

  # MySQL Character Set
  MYSQL_CHARACTER_SET: "utf8mb4"
  MYSQL_COLLATION: "utf8mb4_unicode_ci"
  MYSQL_LOWER_CASE_TABLE_NAMES: "1"
