apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-mobileid-pv
  namespace: egov-app
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "${MOBILEID_CONFIG_PATH}"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-mobileid-pvc
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
