apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-mobileid
  namespace: egov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-mobileid
  template:
    metadata:
      labels:
        app: egov-mobileid
    spec:
      containers:
      - name: egov-mobileid
        image: egovmobileid:k8s
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: egov-common-config
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "80"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: token.accessSecret
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_ACCESS_SECRET
        - name: token.refreshSecret
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_REFRESH_SECRET
        - name: token.accessExpiration
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_ACCESS_EXPIRATION
        - name: token.refreshExpiration
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: TOKEN_REFRESH_EXPIRATION
        - name: roles.roleAdmin
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: ROLES_ROLE_ADMIN
        - name: roles.roleUser
          valueFrom:
            configMapKeyRef:
              name: egov-common-config
              key: ROLES_ROLE_USER
        - name: APP_VERIFY_FILE_PATH
          value: "/app/config/verifyConfig-docker.json"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: egov-mobileid-pvc-nfs  # PVC 사용
---
apiVersion: v1
kind: Service
metadata:
  name: egov-mobileid
  namespace: egov-app
spec:
  selector:
    app: egov-mobileid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
