apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-search
  namespace: egov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-search
  template:
    metadata:
      labels:
        app: egov-search
    spec:
      containers:
      - name: egov-search
        image: egovsearch:k8s
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: egov-common-config
        - secretRef:
            name: mysql-secret
        - secretRef:
            name: opensearch-secret
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "80"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: APP_SEARCH_CONFIG_PATH
          value: "/app/config/searchConfig-k8s.json"
        - name: OPENSEARCH_KEYSTORE_PATH
          value: "/app/cacerts/cacerts"
        - name: OPENSEARCH_KEYSTORE_PASSWORD
          value: "changeit"
        - name: OPENSEARCH_PROTOCOL
          value: "https"
        - name: OPENSEARCH_URL
          value: "opensearch-internal.egov-db.svc.cluster.local"
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_EGOVFRAMEWORK_COM_EXT_OPS
          value: "DEBUG"
        - name: LOGGING_LEVEL_ORG_OPENSEARCH
          value: "DEBUG"
        volumeMounts:
        - name: search-config
          mountPath: /app/config
          readOnly: true
        - name: search-model
          mountPath: /app/model
        - name: search-cacerts
          mountPath: /app/cacerts
          readOnly: true
        - name: search-example
          mountPath: /app/example
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: search-config
        configMap:
          name: search-config
      - name: search-model
        persistentVolumeClaim:
          claimName: search-model-pvc
      - name: search-cacerts
        secret:
          secretName: search-cacerts
      - name: search-example
        persistentVolumeClaim:
          claimName: search-example-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: egov-search
  namespace: egov-app
spec:
  selector:
    app: egov-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
