# Config PV/PVC - hostPath
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-config-pv-hostpath
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "${SEARCH_BASE_PATH}/config"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-config-pvc-hostpath
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard
  volumeName: egov-search-config-pv-hostpath
---
# Config PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-config-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.56.21
    path: "/srv/nfs/data/egov-search/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-config-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-storage
  volumeName: egov-search-config-pv-nfs
---
# Model PV/PVC - hostPath
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-model-pv-hostpath
  namespace: egov-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "${SEARCH_BASE_PATH}/model"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-model-pvc-hostpath
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: egov-search-model-pv-hostpath
---
# Model PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-model-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.56.21
    path: "/srv/nfs/data/egov-search/model"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-model-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
  volumeName: egov-search-model-pv-nfs
---
# Example PV/PVC - hostPath
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-example-pv-hostpath
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "${SEARCH_BASE_PATH}/example"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-example-pvc-hostpath
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard
  volumeName: egov-search-example-pv-hostpath
---
# Example PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-example-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.56.21
    path: "/srv/nfs/data/egov-search/example"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-example-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-storage
  volumeName: egov-search-example-pv-nfs
---
# Cacerts PV/PVC - hostPath
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-cacerts-pv-hostpath
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "${SEARCH_BASE_PATH}/cacerts"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-cacerts-pvc-hostpath
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard
  volumeName: egov-search-cacerts-pv-hostpath
---
# Cacerts PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-cacerts-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.56.21
    path: "/srv/nfs/data/egov-search/cacerts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-cacerts-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-storage
  volumeName: egov-search-cacerts-pv-nfs
