#!/bin/bash
# 이 스크립트는 실행하지 않습니다. 수동 설치 가이드로 사용하세요.

echo "============================================================"
echo "전자정부 표준프레임워크 MSA 공통컴포넌트 Kubernetes 수동 배포 가이드"
echo "============================================================"

echo "1. Istio 설치"
echo "cd /Users/chrisyoon/Projects/egovframe/egovframe-common-components-msa-krds/k8s-deploy/bin"
echo "curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.25.0 TARGET_ARCH=arm64 sh -"
echo "cd istio-1.25.0"
echo "export PATH=\$PWD/bin:\$PATH"
echo "istioctl install --set profile=default -y"
echo "kubectl create namespace egov-app"
echo "kubectl label namespace egov-app istio-injection=enabled"
echo "kubectl apply -f ../../manifests/egov-istio/config.yaml"
echo "kubectl apply -f ../../manifests/egov-istio/telemetry.yaml"
echo "kubectl wait --for=condition=Ready pods --all -n istio-system --timeout=300s"

echo -e "\n2. 네임스페이스 생성"
echo "kubectl create namespace egov-monitoring"
echo "kubectl create namespace egov-db"
echo "kubectl create namespace egov-infra"
echo "kubectl label namespace egov-infra istio-injection=enabled"

echo -e "\n3. 모니터링 설치"
echo "# cert-manager 설치"
echo "kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml"
echo "kubectl wait --for=condition=Ready pods --all -n cert-manager --timeout=300s"

echo "# OpenTelemetry Operator 설치"
echo "kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.120.0/opentelemetry-operator.yaml"
echo "kubectl wait --for=condition=Ready pods -l control-plane=controller-manager -n opentelemetry-operator-system --timeout=300s"

echo "# 모니터링 컴포넌트 설치"
echo "cd ../../manifests/egov-monitoring"
echo "kubectl apply -f alertmanager-config.yaml"
echo "kubectl apply -f circuit-breaker-alerts-configmap.yaml"
echo "kubectl apply -f prometheus.yaml"
echo "kubectl apply -f grafana.yaml"
echo "kubectl apply -f kiali.yaml"
echo "kubectl apply -f jaeger.yaml"
echo "kubectl apply -f loki.yaml"
echo "kubectl apply -f alertmanager.yaml"
echo "kubectl wait --for=condition=Ready pods --all -n egov-monitoring --timeout=300s"

echo -e "\n4. MySQL 설치"
echo "cd ../egov-db"
echo "kubectl apply -f mysql-pv.yaml"
echo "kubectl apply -f mysql-secret.yaml"
echo "kubectl apply -f mysql-statefulset.yaml"
echo "kubectl apply -f mysql-service.yaml"
echo "kubectl rollout status statefulset/mysql -n egov-db --timeout=300s"

echo -e "\n5. OpenSearch 설치"
echo "kubectl apply -f opensearch-pv.yaml"
echo "kubectl apply -f opensearch-configmap.yaml"
echo "kubectl apply -f opensearch-secret.yaml"
echo "kubectl apply -f opensearch-certs-secret.yaml"
echo "kubectl apply -f opensearch-statefulset.yaml"
echo "kubectl apply -f opensearch-service.yaml"
echo "kubectl apply -f opensearch-dashboard-deployment.yaml"
echo "kubectl rollout status statefulset/opensearch -n egov-db --timeout=300s"

echo -e "\n6. 인프라 서비스 설치"
echo "cd ../egov-infra"
echo "kubectl apply -f egov-common-configmap.yaml"
echo "kubectl apply -f rabbitmq-configmap.yaml"
echo "kubectl apply -f rabbitmq-pv.yaml"
echo "kubectl apply -f rabbitmq-deployment.yaml"
echo "kubectl apply -f rabbitmq-service.yaml"
echo "kubectl rollout status deployment/rabbitmq -n egov-infra --timeout=300s"
echo "kubectl apply -f gatewayserver-deployment.yaml"
echo "kubectl rollout status deployment/gateway-server -n egov-infra --timeout=300s"

echo -e "\n7. 애플리케이션 서비스 설치"
echo "cd ../egov-app"
echo "# MySQL Secret 복사 (egov-db -> egov-app)"
echo "kubectl get secret mysql-secret -n egov-db -o yaml | sed 's/namespace: egov-db/namespace: egov-app/' | kubectl apply -f -"
echo "kubectl apply -f egov-common-configmap.yaml"
echo "kubectl apply -f egov-mobileid-pv.yaml"
echo "kubectl apply -f egov-search-pv.yaml"

echo "# 각 서비스 배포"
echo "kubectl apply -f egov-hello-deployment.yaml"
echo "kubectl apply -f egov-main-deployment.yaml"
echo "kubectl apply -f egov-board-deployment.yaml"
echo "kubectl apply -f egov-login-deployment.yaml"
echo "kubectl apply -f egov-author-deployment.yaml"
echo "kubectl apply -f egov-mobileid-deployment.yaml"
echo "kubectl apply -f egov-questionnaire-deployment.yaml"
echo "kubectl apply -f egov-cmmncode-deployment.yaml"
echo "kubectl apply -f egov-search-deployment.yaml"

echo -e "\n설치 상태 확인"
echo "kubectl get pods --all-namespaces"

echo -e "\n접근 정보 확인"
echo "./08-show-access-info.sh"

echo -e "\n주의사항:"
echo "1. 각 명령어는 순서대로 실행해야 합니다."
echo "2. 각 단계에서 오류가 발생하면 다음 단계로 진행하기 전에 해결해야 합니다."
echo "3. kubectl wait 명령어는 리소스가 준비될 때까지 대기합니다."
echo "4. 실제 환경에 따라 일부 경로나 설정을 조정해야 할 수 있습니다."