server:
  port: 0 # random port

spring:
  application:
    name: EgovMain
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local
    
logging:
  level:
    org:
      egovframe:
        rte: debug
      springframework:
        boot:
          autoconfigure: error
        web: debug
    egovframework:
      com: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info

---
spring:
  config:
    activate:
      on-profile: k8s
    import: 'optional:configserver:' # Config 서버 비활성화
  cloud:
    config:
      enabled: false # Config 클라이언트 비활성화
    discovery:
      enabled: false # Eureka Discovery 비활성화

eureka:
  client:
    enabled: false # Eureka 클라이언트 비활성화

server:
  port: 80 # k8s 환경에서 모든 서비스가 80 포트 사용