# NFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-nfs
  labels:
    type: nfs
    app: prometheus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/prometheus"
---
# NFS PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-nfs
  namespace: egov-monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: prometheus-pv-nfs
  storageClassName: standard
