apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: egov-db
type: Opaque
data:
  # echo -n 'root' | base64
  MYSQL_ROOT_PASSWORD: cm9vdA==
  # echo -n 'com' | base64
  SPRING_DATASOURCE_USERNAME: Y29t
  # echo -n 'com01' | base64
  SPRING_DATASOURCE_PASSWORD: Y29tMDE=
  # echo -n 'com' | base64
  MYSQL_DATABASE: Y29t
