# hostPath PersistentVolume
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-hostpath
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: standard
#   hostPath:
#     path: "/Users/chrisyoon/Projects/egovframe/egovframe-common-components-msa-krds/k8s-deploy/data/mysql"
#     type: DirectoryOrCreate

---
# hostPath PersistentVolumeClaim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc-hostpath
#   namespace: egov-db
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard
#   volumeName: mysql-pv-hostpath

---
# NFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.21  # Replace with your NFS server IP
    path: "/srv/nfs/data/mysql"

---
# NFS PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nfs
  namespace: egov-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv-nfs
