apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: egov-db
spec:
  type: NodePort
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30920
  - name: performance
    port: 9600
    targetPort: 9600
    nodePort: 30960
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: egov-db
spec:
  clusterIP: None
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
