# NFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/opensearch"

---

# NFS PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc-nfs
  namespace: egov-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: opensearch-pv-nfs
  storageClassName: standard
