apiVersion: v1
kind: Secret
metadata:
  name: opensearch-certs
  namespace: egov-db
type: Opaque
stringData:
  esnode.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDUzCCAjugAwIBAgIJAM6ZFvxW/OApMA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNV
    BAMMEGVnb3Ytb3BlbnNlYXJjaDAeFw0yNDAzMjAwMDAwMDBaFw0yNTAzMjAwMDAw
    MDBaMBsxGTAXBgNVBAMMEGVnb3Ytb3BlbnNlYXJjaDCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBANqS3+vz+UApa4gC9U0RXYt4Fh4yJ4YsdHM8mU4h4k1v
    F9q9Z9ZxG4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    -----END CERTIFICATE-----
  esnode-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDakv/r8/lAKWuI
    AvVNEV2LeBYeMieGLHRzPJlOIeJNbxfavWfWcRuGeGeGeGeGeGeGeGeGeGeGeGeG
    eGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeG
    eGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeG
    eGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeG
    eGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeGeG
    -----END PRIVATE KEY-----
  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDUzCCAjugAwIBAgIJAM6ZFvxW/OApMA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNV
    BAMMEGVnb3Ytb3BlbnNlYXJjaDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBANqS3+vz+UApa4gC9U0RXYt4Fh4yJ4YsdHM8mU4h4k1vF9q9Z9ZxG4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4Z4
    -----END CERTIFICATE-----
