# hostPath PersistentVolume (commented out)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv-hostpath
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/Users/chrisyoon/Projects/egovframe/egovframe-common-components-msa-krds/k8s-deploy/data/opensearch"
    type: DirectoryOrCreate

---

# hostPath PersistentVolumeClaim (commented out)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc-hostpath
  namespace: egov-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: opensearch-pv-hostpath
