apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: egov-db
data:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    node.name: ${HOSTNAME}
    discovery.type: single-node
    bootstrap.memory_lock: true
    network.host: 0.0.0.0
    
    # 보안 설정 비활성화
    plugins.security.disabled: true
