apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: egov-db
spec:
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30920
  - name: performance
    port: 9600
    targetPort: 9600
    nodePort: 30960
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-internal
  namespace: egov-db
spec:
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  clusterIP: None