apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: egov-db
spec:
  clusterIP: None
  ports:
  - port: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: egov-db
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
  selector:
    app: postgresql
    statefulset.kubernetes.io/pod-name: postgresql-0