apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: egov-db
type: Opaque
data:
  redis-password: dGhxa2QxMTkh  # "thqkd119!"를 base64로 인코딩한 값

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: egov-db
  labels:
    app: redis
spec:
  serviceName: "redis-headless"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2.4-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: data
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        imagePullPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-redis-0

---          

apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: egov-db
  labels:
    app: redis
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: egov-db
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: egov-db
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
      name: redis
  selector:
    app: redis