---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: egov-cicd
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30011  # Jenkins Web UI용 포트
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 30010  # Jenkins Agent 연결용 포트
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: egov-cicd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30012
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: egov-cicd
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30013
  selector:
    app: sonarqube
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: egov-cicd
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30014
  selector:
    app: nexus
