apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: egov-cicd
data:
  gitlab.rb: |
    external_url 'http://gitlab.example.com'
    
    # Redis 설정
    # gitlab.rb 수정
    redis['enable'] = false

    gitlab_rails['redis_host'] = "gitlab-redis.egov-cicd.svc.cluster.local"
    gitlab_rails['redis_port'] = 6379


    # Puma 설정
    puma['enable'] = true
    puma['worker_processes'] = 2
    puma['max_threads'] = 4
    puma['min_threads'] = 1
    puma['listen'] = '0.0.0.0'
    puma['port'] = 9292
    puma['worker_timeout'] = 60

    # Workhorse 설정
    gitlab_workhorse['enable'] = true
    gitlab_workhorse['listen_network'] = 'tcp'
    gitlab_workhorse['listen_addr'] = '0.0.0.0:8282'
    gitlab_workhorse['backend'] = 'http://127.0.0.1:9292'

    nginx['enable'] = false

    # Rails 설정
    gitlab_rails['env'] = {
      'RAILS_ENV' => 'production'
    }

    # PostgreSQL 설정
    postgresql['enable'] = false
    gitlab_rails['db_adapter'] = "postgresql"
    gitlab_rails['db_encoding'] = "unicode"
    gitlab_rails['db_database'] = "gitlabhq_production"
    gitlab_rails['db_username'] = "gitlab"
    gitlab_rails['db_password'] = "gitlab-password"
    gitlab_rails['db_host'] = "postgresql.egov-db.svc.cluster.local"
    gitlab_rails['db_port'] = 5432

    # 시스템 설정
    unicorn['enable'] = false
    sidekiq['enable'] = true
    prometheus_monitoring['enable'] = false

    # Gitaly 설정 (runtime_dir 제거됨)
    gitaly['enable'] = true
    gitaly['configuration'] = {
      storage: [
        {
          name: 'default',
          path: '/var/opt/gitlab/git-data'
        }
      ]
    }
