apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: egov-cicd
spec:
  serviceName: gitlab-headless
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      securityContext:
        fsGroup: 998  # git group
      initContainers:
      - name: init-gitlab
        image: busybox
        command: 
        - /bin/sh
        - -c
        - |
          mkdir -p /var/opt/gitlab/gitlab-workhorse/sockets
          chmod -R 777 /var/opt/gitlab/gitlab-workhorse
        volumeMounts:
        - name: gitlab-workhorse
          mountPath: /var/opt/gitlab/gitlab-workhorse
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:16.10.1-ce.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-config-file
          mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: gitlab-workhorse
          mountPath: /var/opt/gitlab/gitlab-workhorse
        - name: ssh-host-keys
          mountPath: /etc/ssh
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "12Gi"
      volumes:
      - name: gitlab-config
        hostPath:
          path: ${DATA_BASE_PATH}/gitlab/config
          type: DirectoryOrCreate
      - name: gitlab-config-file
        configMap:
          name: gitlab-config
      - name: gitlab-logs
        hostPath:
          path: ${DATA_BASE_PATH}/gitlab/logs
          type: DirectoryOrCreate
      - name: gitlab-data
        hostPath:
          path: ${DATA_BASE_PATH}/gitlab/data
          type: DirectoryOrCreate
      - name: gitlab-workhorse
        hostPath:
          path: ${DATA_BASE_PATH}/gitlab/workhorse
          type: DirectoryOrCreate
      - name: ssh-host-keys
        hostPath:
          path: ${DATA_BASE_PATH}/gitlab/ssh
          type: DirectoryOrCreate
