apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-redis
  namespace: egov-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-redis
  template:
    metadata:
      labels:
        app: gitlab-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis
  namespace: egov-cicd
spec:
  selector:
    app: gitlab-redis
  ports:
    - port: 6379
