apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: egov-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9-community
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
      volumes:
      - name: sonarqube-data
        hostPath:
          path: /Users/chrisyoon/Projects/egovframe/egovframe-common-components-msa-krds/k8s-deploy/data/sonarqube
          type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: egov-cicd
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30013
  selector:
    app: sonarqube
