apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: egov-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9-community
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
      volumes:
      - name: sonarqube-data
        hostPath:
          path: ${DATA_BASE_PATH}/sonarqube
          type: DirectoryOrCreate